"""Add last_redirect and redirect_count columns

Revision ID: a737043ea658
Revises: fdfd44639dde
Create Date: 2025-08-06 19:32:23.671007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a737043ea658'
down_revision: Union[str, Sequence[str], None] = 'fdfd44639dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_mappings', sa.Column('last_redirect', sa.DateTime(timezone=True), nullable=True))
    op.add_column('url_mappings', sa.Column('redirect_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url_mappings', 'redirect_count')
    op.drop_column('url_mappings', 'last_redirect')
    # ### end Alembic commands ###
