"""Initial migration

Revision ID: fdfd44639dde
Revises: 
Create Date: 2025-08-06 17:55:29.143337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdfd44639dde'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_mappings',
    sa.Column('shortcode', sa.String(length=255), nullable=False),
    sa.Column('original_url', sa.String(length=2048), nullable=False),
    sa.Column('update_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('shortcode'),
    sa.UniqueConstraint('update_id')
    )
    op.create_index(op.f('ix_url_mappings_shortcode'), 'url_mappings', ['shortcode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_mappings_shortcode'), table_name='url_mappings')
    op.drop_table('url_mappings')
    # ### end Alembic commands ###
